### ISSUE TITLE
Could not find match for ^/w+/W

### ISSUE THREAD

**Issue by Shawn9347** [BananaPukeh/plex-music-grabber#1]
Evening,

I just tried to run your docker container. It seemed really awesome. However I am getting this error. See below.

`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/app/grabber.py", line 104, in <module>
    scanLibrary()
  File "/app/grabber.py", line 29, in scanLibrary
    grabMusic(name)
  File "/app/grabber.py", line 61, in grabMusic
    hiStream = yt.streams.get_audio_only("mp4")
  File "/usr/local/lib/python3.9/site-packages/pytube/__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "/usr/local/lib/python3.9/site-packages/pytube/__main__.py", line 188, in fmt_streams
    extract.apply_signature(stream_manifest, self.vid_info, self.js)
  File "/usr/local/lib/python3.9/site-packages/pytube/extract.py", line 409, in apply_signature
    cipher = Cipher(js=js)
  File "/usr/local/lib/python3.9/site-packages/pytube/cipher.py", line 33, in __init__
    raise RegexMatchError(
pytube.exceptions.RegexMatchError: __init__: could not find match for ^\w+\W`

**Comment by BananaPukeh** [comment]
Hey thanks for the feedback!

Can you see in the logs on which tv-show it crashes?

**Comment by Shawn9347** [comment]
Yes. Star wars rebels. I put a .themeignore file in that directory and than It went to another show, same error. That show is The end of the f*cking world.

**Comment by BananaPukeh** [comment]
Allright, sounds like the YouTube download security is updated again. 

I suppose updating the dependencies (pytube) will just fix the issue. I will look into it

**Comment by Shawn9347** [comment]
Nice. I look forward to using your container.

**Comment by BananaPukeh** [comment]
Seems like another pytube bug: https://github.com/pytube/pytube/issues/1199 

Will look into it tomorrow.

**Comment by Shawn9347** [comment]
Thanks

**Comment by BananaPukeh** [comment]
Moved away from the pytube library. 

Fixed in version 1.1.0

**Comment by Shawn9347** [comment]
Great! The error is gone. I am getting a permission denied error right now. Any ideas?

**Comment by BananaPukeh** [comment]
What kind of error?

**Comment by Shawn9347** [comment]
I fixed it. I changed folder permissions. It's downloading theme songs right now. Thanks!!!
