### ISSUE TITLE
Its downloading trailers audio for movvies

### ISSUE THREAD

**Issue by ashipaek0** [BananaPukeh/plex-music-grabber#5]
Its downloading trailer audio.  (dialog) for content

and it looks like it doesnt check for size. there's content 3 minutes long.  thats not theme music, is it?

Check the link....

```
plex-music-grabber    | === Plex Music Grabber ===
plex-music-grabber    | Start running with an interval of 3600
plex-music-grabber    | Notify:  Start updating theme songs for 2 libraries
plex-music-grabber    | Downloading theme song from http://www.youtube.com/watch?v=BVtN9rwoGpw
plex-music-grabber    | [youtube] BVtN9rwoGpw: Downloading webpage
plex-music-grabber    | [youtube] BVtN9rwoGpw: Downloading android player API JSON
plex-music-grabber    | [info] BVtN9rwoGpw: Downloading 1 format(s): 251
plex-music-grabber    | [download] Destination: /library/movies/About Fate (2022)/theme.webm
plex-music-grabber    | [download] Download completed
plex-music-grabber    | [ExtractAudio] Destination: /library/movies/About Fate (2022)/theme.mp3
plex-music-grabber    | Deleting original file /library/movies/About Fate (2022)/theme.webm (pass -k to keep)
plex-music-grabber    | Notify:  Downloaded theme song for 'About Fate (2022)'


```

**Comment by BananaPukeh** [comment]
Hi, thanks for making a ticket.

This is something I've noticed myself as well. However, for movies, there is not always a theme song / original soundtrack available.

The program searches using the following terms:
```
{folder name} ('ost' | 'theme song' | 'op' | 'opening') 
```
Extra filters: 
- less than 4 minutes
- type: video

So with the given movie name:
```
About Fate (2022) ('ost' | 'theme song' | 'op' | 'opening') 
```

See the results yourself:
https://www.youtube.com/results?search_query=About+Fate+%282022%29+%28%27ost%27+%7C+%27theme+song%27+%7C+%27op%27+%7C+%27opening%27%29&sp=EgQQARgB

A possible solution is to completely filter out "trailers" by appending `-trailer` to the search query. But the problem with media without a theme song, is that there won't be any relevant results. 

Result with `-trailer` query
https://www.youtube.com/results?search_query=About+Fate+%282022%29+%28%27ost%27+%7C+%27theme+song%27+%7C+%27op%27+%7C+%27opening%27%29+-trailer&sp=EgIYAQ%253D%253D


So, if you have any ideas how to tackle this problem, I'll be happy to implement this.
